# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/{{ cookiecutter.app_name }}-baseimage:_BASE_TAG_
ENV {{ cookiecutter.app_name | upper }}_CFG_PATH /etc/{{ cookiecutter.github_name }}/{{ cookiecutter.app_name }}
VOLUME /etc/{{ cookiecutter.github_name }}/{{ cookiecutter.app_name }}
ADD  payload/sampleconfig.tar.bz2 ${{ cookiecutter.app_name | upper }}_CFG_PATH
