# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _NS_/{{ cookiecutter.app_name }}-buildenv:_TAG_

# fabric configuration locations
ENV FABRIC_CFG_PATH /etc/{{ cookiecutter.github_username }}/{{ cookiecutter.app_name }}

# create needed directories
RUN mkdir -p \
  $FABRIC_CFG_PATH \
  /var/{{ cookiecutter.github_username }}/production

# fabric configuration files
ADD payload/sampleconfig.tar.bz2 $FABRIC_CFG_PATH

# typically, this is mapped to a developer's dev environment
WORKDIR /opt/gopath/src/github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.app_name }}
