# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/{{ cookiecutter.app_name }}-baseimage:_BASE_TAG_
COPY payload/gotools.tar.bz2 /usr/local/bin/
RUN go install -a std
