# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

unit-tests:
  image: {{ cookiecutter.github_username }}/{{ cookiecutter.app_name }}-testenv
  environment:
    - GO_LDFLAGS
    - GO_TAGS
    - OUTPUT
    - TEST_PKGS=${TEST_PKGS}
    - CORE_VM_DOCKER_ATTACHSTDOUT=true
    - VERBOSE
    - JOB_TYPE=${JOB_TYPE}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${GOPATH}/src/github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.app_name }}:/opt/gopath/src/github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.app_name }}
  command: ./unit-test/run.sh
